[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    baseUrl = "https://example.com"
